backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'static/images/uploads' # Media files will be stored in the repo under static/images/uploads
public_folder: '/images/uploads' # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - name: 'home'
        label: 'Home'
        file: 'content/pages/home.json'
        fields:
          - name: 'bannerMessage'
            label: 'Banner Message'
            widget: 'string'
          - name: 'bannerButton'
            label: 'Banner Button'
            widget: 'string'
      - name: 'connect'
        label: 'Connect'
        file: 'content/pages/connect.json'
        fields:
          - name: 'gospelCommunities'
            label: 'Gospel Communities'
            label_singular: 'Gospel Community'
            widget: 'list'
            fields:
              - name: 'hosts'
                label: 'Hosts'
                widget: 'string'
              - name: 'address'
                label: 'Address'
                widget: 'string'
              - name: 'subaddress'
                label: 'Subaddress'
                widget: 'string'
              - name: 'time'
                label: 'Time'
                widget: 'string'
              - name: 'moreInfo'
                label: 'More Info'
                widget: 'text'
      - name: 'about'
        label: 'About'
        file: 'content/pages/about.json'
        fields:
          - name: 'staff'
            label: 'Staff'
            label_singular: Staff Member
            widget: list
            fields:
              - name: 'name'
                label: 'Name'
                widget: 'string'
              - name: 'role'
                label: 'Role'
                widget: string
                required: false
              - name: 'summary'
                label: Summary
                widget: markdown
                required: false
              - name: 'email'
                label: 'Email'
                widget: 'string'
                required: false
              - name: 'phone'
                label: 'Phone'
                widget: 'string'
                required: false
              - name: imgUrl
                label: Image URL
                widget: string
                required: false
          - name: beliefs
            label: Beliefs
            label_singular: 'Belief'
            widget: list
            fields:
              - name: 'title'
                label: 'Title'
                widget: 'string'
              - name: 'description'
                label: 'Description'
                widget: 'markdown'
  - name: series
    label: Series
    folder: content/sermons/series
    extension: json
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: description
        label: Description
        widget: 'markdown'
        required: false
      - name: image
        label: Image
        widget: image
        required: false
  - name: sermonLists
    label: Sermon Lists
    label_singular: Sermon List
    folder: content/sermons/year
    extension: json
    create: true
    fields:
      - name: title
        label: Year
        widget: string
      - name: sermons
        label: Sermons
        label_singular: Sermon
        widget: list
        required: false
        fields:
          - name: title
            label: Title
            widget: string
          - name: date
            label: Date
            widget: date
          - name: 'series'
            label: 'Series'
            widget: 'relation'
            collection: 'series'
            searchFields: ['title']
            valueField: 'title'
            required: false
          - name: leader
            label: Leader
            widget: select
            options:
              [
                'Jeremy Buck',
                'Dan Fowler',
                'Paul Rayburn',
                'Ky Martin',
                'David Ritchie',
                'Jacob Cates',
                'Andrew Merker',
                'Cody M',
                'Dusty Thompson',
                'Todd Blackhurst',
              ]
            valueField: 'name'
            required: false
          - name: 'summary'
            label: 'Summary'
            widget: 'markdown'
            required: false
          - name: 'podcastUrl'
            label: 'Podcast URL'
            widget: 'string'
            required: false
          - name: 'files'
            label: 'Files'
            widget: 'list'
            required: false
            fields:
              - name: title
                label: Title
                widget: string
              - name: file
                label: File
                widget: file
                required: false
              - name: url
                label: URL
                widget: string
                required: false
